script: "bundle exec rspec spec && bundle exec cucumber features"

rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx

branches:
  only:
    - master
    - development
