name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
    - name: Install Bundler and Gems
      run: |
        gem install bundler -v 2.3.26
        bundle install
    - name: Run Cucumber
      run: |
        bundle exec rake features
    - name: Run RSpec
      run: |
        bundle exec rake spec
